### ISSUE TITLE
Use Slim urlFor method to get views URL

### ISSUE THREAD

**Issue by peloyeje** [featherbb/featherbb#62]

**Comment by beaver-dev** [comment]
We may have to change the way pagination is set in URLs : the urlFor() method requires to fill all the non-optional parameters declared in the `routes.php` file.
i.e. in `style/themes/FeatherBB/view/delete.php`, we should replace breadcrumb line 20 with 

```
<li><span>»&#160;</span><a href="<?= $feather->urlFor('viewForum', array('id'=>$cur_post['fid'], 'name'=>$feather->url->url_friendly($cur_post['forum_name']),'page'=>'1')) ?>"><?= $feather->utils->escape($cur_post['forum_name']) ?></a></li>
```

Wouldn't the urls be cleaner without the page number ? I suggest we go back to `?page=N`, and get the value in controllers with request params. But we can also capture it in a regex on the current urls, or even build urls as `$feather->get('/:id(/:name)(/:page)(/)'` instead of `$feather->get('/:id(/:name)(/page/:page)(/)'`, so that page value is really optional, as you want.

**Comment by adaur** [comment]
No, we won't go back to ugly parameters, or worst: unneeded requests. Maybe you could write a new function that would do the trick between our app and Slim ?

Anyway, I think the router has been entirely redesigned in Slim v3. Maybe it will be more flexible?

http://www.slimframework.com/docs/objects/router.html

**Comment by beaver-dev** [comment]
Sure, a new function would be the best solution :) I'll look into it soon.

**Comment by beaver-dev** [comment]
All good !

https://github.com/featherbb/featherbb/commit/4f210388f1aa6896245b332c7186790557fae99d
